const wordBank = [
	'a',
	'about',
	'all',
	'also',
	'and',
	'as',
	'at',
	'be',
	'because',
	'but',
	'by',
	'can',
	'come',
	'could',
	'day',
	'do',
	'even',
	'find',
	'first',
	'for',
	'from',
	'get',
	'give',
	'go',
	'have',
	'he',
	'her',
	'here',
	'him',
	'his',
	'how',
	'i',
	'if',
	'in',
	'into',
	'it',
	'its',
	'just',
	'know',
	'like',
	'look',
	'make',
	'man',
	'many',
	'me',
	'more',
	'my',
	'new',
	'no',
	'not',
	'now',
	'of',
	'on',
	'one',
	'only',
	'or',
	'other',
	'our',
	'out',
	'people',
	'say',
	'see',
	'she',
	'so',
	'some',
	'take',
	'tell',
	'than',
	'that',
	'the',
	'their',
	'them',
	'then',
	'there',
	'these',
	'they',
	'thing',
	'think',
	'this',
	'those',
	'time',
	'to',
	'two',
	'up',
	'use',
	'very',
	'want',
	'way',
	'we',
	'well',
	'what',
	'when',
	'which',
	'who',
	'will',
	'with',
	'would',
	'year',
	'you',
	'your',
]

// const sentences = [
// 	'He turned in the research paper on Friday; otherwise, he would have not passed the class.',
// 	'It was a really good Monday for being a Saturday.',
// 	'I received a heavy fine but it failed to crush my spirit.'
// ]

const sentences = [ "Birds migrate south for the winter to escape colder temperatures.", "Plants need sunlight, water, and nutrients to grow.", "The Earth orbits around the Sun once every 365 days.", "Water boils at 100 degrees Celsius.", "The Great Wall of China is one of the seven wonders of the world.", "The human body is made up of billions of cells.", "The Amazon Rainforest is home to a diverse range of wildlife.", "Photosynthesis is the process by which plants make their own food.", "The moon has phases because of its orbit around the Earth.", "Mount Everest is the tallest mountain in the world.", "The Declaration of Independence was signed in 1776.", "The Statue of Liberty was a gift from France to the United States.", "Electricity is the flow of electric charge through a conductor.", "The Pacific Ocean is the largest ocean on Earth.", "The human brain is the most complex organ in the body.", "A rainbow forms when sunlight is refracted by water droplets in the air.", "The Eiffel Tower is located in Paris, France.", "The Sahara Desert is the largest hot desert in the world.", "DNA contains the genetic instructions for the development and functioning of living organisms.", "The United States has 50 states.", "The Titanic sank in 1912 after hitting an iceberg.", "Gravity is the force that pulls objects toward each other.", "The Nile River is the longest river in the world.", "The Mona Lisa is a famous painting by Leonardo da Vinci.", "The human heart pumps blood throughout the body.", "The Statue of Liberty stands on Liberty Island in New York Harbor.", "The Colosseum is an ancient amphitheater located in Rome, Italy.", "The Earth's atmosphere is composed of nitrogen, oxygen, and other gases.", "Astronauts wear spacesuits to protect themselves in space.", "The Louvre Museum is home to the Mona Lisa and other famous artworks.", "The Arctic Circle is located at the northernmost part of the Earth.", "The Wright brothers made the first successful powered flight in 1903.", "The human skeleton provides structure and support for the body.", "Tornadoes are rapidly rotating columns of air that occur during severe thunderstorms.", "The Pyramids of Giza are ancient structures located in Egypt.", "The Indian Ocean is the third largest ocean on Earth.", "The human respiratory system includes organs such as the lungs and trachea.", "The Big Bang theory is the prevailing cosmological model for the observable universe.", "The Golden Gate Bridge is a suspension bridge located in San Francisco, California.", "Volcanoes erupt when magma rises to the surface of the Earth.", "The Mona Lisa is housed in the Louvre Museum in Paris, France.", "The human digestive system breaks down food into nutrients that the body can use.", "The Taj Mahal is a mausoleum located in Agra, India.", "The Statue of Liberty was dedicated on October 28, 1886.", "The Andes Mountains are the longest mountain range in the world.", "The International Space Station orbits around the Earth.", "The Berlin Wall separated East and West Berlin during the Cold War.", "The human immune system defends the body against pathogens.", "The Grand Canyon is a steep-sided canyon carved by the Colorado River in Arizona, USA.", "The Leaning Tower of Pisa is a famous leaning bell tower located in Italy.", "Hurricanes are large, powerful storms that form over warm ocean waters.", "The Parthenon is an ancient temple located in Athens, Greece.", "The Great Barrier Reef is the largest coral reef system in the world.", "The human circulatory system includes the heart, blood vessels, and blood.", "The Great Pyramid of Giza is the oldest and largest of the three pyramids in Giza, Egypt.", "The Empire State Building is a skyscraper located in New York City.", "The moon's gravitational pull causes tides on Earth.", "The Panama Canal is a man-made waterway that connects the Atlantic Ocean to the Pacific Ocean.", "The human nervous system transmits signals between the brain and the body.", "The Red Sea is a seawater inlet of the Indian Ocean between Africa and Asia.", "The Louvre Museum is one of the largest and most visited museums in the world.", "The human reproductive system allows for the production of offspring.", "The Sahara Desert covers much of North Africa and is the hottest desert in the world.", "The Mayan civilization flourished in Mesoamerica from about 2000 BCE to 900 CE.", "The Golden Gate Bridge spans the Golden Gate Strait, the entrance to the San Francisco Bay.", "The human endocrine system regulates hormones and other chemical messengers.", "The Great Wall of China stretches over 13,000 miles across northern China.", "The human muscular system allows for movement and stability.", "The Moon is Earth's only natural satellite.", "The Sistine Chapel ceiling was painted by Michelangelo.", "The human excretory system removes waste products from the body.", "The Sahara Desert is roughly the size of the United States.", "The human integumentary system includes the skin, hair, and nails.", "The Sahara Desert is expanding due to desertification.", "The human urinary system filters waste products from the blood and produces urine.", "The Sahara Desert experiences extreme temperature variations between day and night.", "The human lymphatic system helps maintain fluid balance and defend against infections.", "The Sahara Desert is largely uninhabited, but some nomadic tribes live there.", "The human skeletal system is composed of bones, cartilage, and joints.", "The Sahara Desert is characterized by its vast sand dunes and rocky plateaus.", "The human reproductive system includes organs such as the ovaries and testes.", "The Sahara Desert receives very little rainfall, making it one of the driest places on Earth.", "The human cardiovascular system transports oxygen, nutrients, and hormones throughout the body.", "The Sahara Desert was once home to ancient civilizations such as the Egyptians and Berbers.", "The Sahara Desert is a challenging environment for plant and animal life to survive.", "The Sahara Desert is located in Africa and spans several countries including Morocco, Algeria, and Egypt.", "The Sahara Desert is a popular destination for adventure tourism and desert safaris." ] 

export default sentences